package com.carlos.grabredenvelope.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.carlos.grabredenvelope.db.WechatRedEnvelope;

import com.carlos.grabredenvelope.db.WechatRedEnvelopeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wechatRedEnvelopeDaoConfig;

    private final WechatRedEnvelopeDao wechatRedEnvelopeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wechatRedEnvelopeDaoConfig = daoConfigMap.get(WechatRedEnvelopeDao.class).clone();
        wechatRedEnvelopeDaoConfig.initIdentityScope(type);

        wechatRedEnvelopeDao = new WechatRedEnvelopeDao(wechatRedEnvelopeDaoConfig, this);

        registerDao(WechatRedEnvelope.class, wechatRedEnvelopeDao);
    }
    
    public void clear() {
        wechatRedEnvelopeDaoConfig.clearIdentityScope();
    }

    public WechatRedEnvelopeDao getWechatRedEnvelopeDao() {
        return wechatRedEnvelopeDao;
    }

}
