package com.carlos.grabredenvelope.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.carlos.grabredenvelope.db.WechatRedEnvelope;
import com.carlos.grabredenvelope.db.DingDingRedEnvelope;

import com.carlos.grabredenvelope.db.WechatRedEnvelopeDao;
import com.carlos.grabredenvelope.db.DingDingRedEnvelopeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wechatRedEnvelopeDaoConfig;
    private final DaoConfig dingDingRedEnvelopeDaoConfig;

    private final WechatRedEnvelopeDao wechatRedEnvelopeDao;
    private final DingDingRedEnvelopeDao dingDingRedEnvelopeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wechatRedEnvelopeDaoConfig = daoConfigMap.get(WechatRedEnvelopeDao.class).clone();
        wechatRedEnvelopeDaoConfig.initIdentityScope(type);

        dingDingRedEnvelopeDaoConfig = daoConfigMap.get(DingDingRedEnvelopeDao.class).clone();
        dingDingRedEnvelopeDaoConfig.initIdentityScope(type);

        wechatRedEnvelopeDao = new WechatRedEnvelopeDao(wechatRedEnvelopeDaoConfig, this);
        dingDingRedEnvelopeDao = new DingDingRedEnvelopeDao(dingDingRedEnvelopeDaoConfig, this);

        registerDao(WechatRedEnvelope.class, wechatRedEnvelopeDao);
        registerDao(DingDingRedEnvelope.class, dingDingRedEnvelopeDao);
    }
    
    public void clear() {
        wechatRedEnvelopeDaoConfig.clearIdentityScope();
        dingDingRedEnvelopeDaoConfig.clearIdentityScope();
    }

    public WechatRedEnvelopeDao getWechatRedEnvelopeDao() {
        return wechatRedEnvelopeDao;
    }

    public DingDingRedEnvelopeDao getDingDingRedEnvelopeDao() {
        return dingDingRedEnvelopeDao;
    }

}
